#!/usr/bin/env bash
# This script that displays numbers from 1 to 20 and different expresions in different iterations.
count=0
while [ $count -le 19 ]
do
    echo $count
    case "$count" in
        3) echo "bad luck from China";;
        8) echo "bad luck from Japan";;
        16) echo "bad luck from Italy";;
        esac
        ((count++))
done
