#!/usr/bin/env bash
# This script that the content of the current directory, in a list format where only part of the name after the first dash.
list=$(ls)
for i in $list
do
    echo "$i" | cut -d' ' -f 2
done
