#!/usr/bin/env bash
# This script that gives you information about the school file.
file="school"
if [ -e $file ]; then
    echo "school file exists"
else
    echo "school file does not exist"
    exit 1

fi
if [ ! -s $file ]; then
    echo "school file is empty"
else
    echo "school files is not empty"
fi
if [ -f $file ]; then
    echo "school file is a regular file"
fi

